### PR TITLE
feat: plane following track on scroll

### PR DESCRIPTION
**Pull request by wgao19**
Implement #6

### CODE REVIEW

**Comment by kemingy** [comment]
Let me check the Cloudflare configuration.

**Comment by wgao19** [comment]
@kemingy seems that the build has issue on loading css as I got this cross-origin warning:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://design.mapotofu.org/style.css with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

But I can't replicate the issue locally. I'm not sure if it's a problem of my company laptop's policy. Can you help take a look please?

**Comment by kemingy** [comment]
> @kemingy seems that the build has issue on loading css as I got this cross-origin warning:
> 
> ```
> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://design.mapotofu.org/style.css with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
> ```
> 
> But I can't replicate the issue locally. I'm not sure if it's a problem of my company laptop's policy. Can you help take a look please?

Looks like it's related to the build method. Did you build it with `zola serve` or `zola build`? By default, if you use `zola serve`, it should replace all the `base_url`. The Cloudflare pager may not be able to handle this very well. I'm going to merge this.

**Comment by kemingy** [comment]
Weird. The online CSS doesn't contain the `#track` and `#plane` parts.

**Comment by kemingy** [comment]
> Weird. The online CSS doesn't contain the `#track` and `#plane` parts.

It works now. I guess it might be a Cloudflare CDN bug. Not sure why the current `style.css` is correct. Will check the configuration.

**Pull request merged**
